todo_application/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='todos/')),  # Redirect to todos/
    path('todos/', include('todos.urls')),
    path('admin/', admin.site.urls),
]

todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'
urlpatterns = [
    path('', views.index, name='index'),
    path('addTodo/', views.addTodo, name='addTodo'),
    path('addCategory/', views.addCategory, name='addCategory'),
    path('<int:todo_id>/edit/', views.edit, name='edit'),
    path('<int:todo_id>/update/', views.update, name='update'),
    path('<int:todo_id>/delete/', views.delete, name='delete'),
    path('search/', views.search,  name='search'),
    
]

todos/models.py
from django.db import models
from django.core.exceptions import ValidationError
import datetime

'''
entity: Category
attributes:
    category_name - the name of the category
    todo_count - number of tasks under the category
'''
class Category(models.Model):
    category_name = models.CharField(max_length=100)
    todo_count = models.IntegerField(default=0)

    def __str__(self):
        return self.category_name


'''
attribute of Todo: notification_time
'''
class NotificationTime(models.Model):
    notification_time = models.CharField(max_length=400, null=True)

    def __str__(self):
        return self.notification_time

'''
entity: Todo
attributes:
    todo_text - text in task
    date_created - date the task was created
    due_date - date the task is due
    email_notification - contains the email address to send notification to
    category - the category the task belongs to (this is a foreign key, [ todos M>------1 category ] )
    notification_time - time when to notify user
    send_reminder - whether to send reminder or not
'''
class Todo(models.Model):
    todo_text = models.CharField(max_length=1000)
    date_created = models.DateTimeField(default=datetime.datetime.now)
    due_date = models.DateTimeField('due_date', null=True)
    email_notification = models.EmailField(max_length=500, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    notification_time = models.CharField(max_length=400, null=True)
    sent_reminder = models.CharField(max_length=10, default="False")

    def clean(self):
        if self.due_date is not None and self.date_created is not None:
            if self.due_date < self.date_created:
                raise ValidationError("Due date cannot be before the date created.")

todos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Todo, Category, NotificationTime
import dateutil.parser as parser
from django.core.mail import send_mail
from django.http import HttpResponse
from datetime import datetime, time
import sqlite3
import time, traceback
import threading
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

def get_common_data():
    todo_items = Todo.objects.order_by('-due_date')[:10]
    category_items = Category.objects.all()
    notification_time = NotificationTime.objects.all()

    current_date_time = datetime.now()
    dt_string = current_date_time.strftime("%m/%d/%Y %I:%M %p")
    splited_dt_string = dt_string.split(" ")

    # check if category exists
    show_add_task = Category.objects.count() > 0;

    return {
        'todo_items': todo_items,
        'category_items': category_items,
        'notification_time' : notification_time,
        'hide_side_bar' : False,
        'current_date': splited_dt_string[0] + str().join(" ") + splited_dt_string[1] + str().join(" ") + splited_dt_string[2],
        'show_add_task': show_add_task,
    }

def index(request):
    context = get_common_data()
    # check if a category exists
    return render(request, 'todos/index.html', context)

def search(request):
    if request.method == "POST":
        searched = request.POST['searched']
        Todos = Todo.objects.filter(todo_text__iexact=searched)
        context = get_common_data()
        context.update({
            'searched': searched,
            'Todos': Todos,
        })
        return render(request, 'todos/search.html', context)
    else:
        return render(request, 'todos/search.html', {})

    

def addTodo(request):
    receiver_email = ""
    notification_time = "not available"

    if 'email_notification' in request.POST:
        receiver_email = request.POST['email_notification']

    if 'todo_notification_time' in request.POST:
        notification_time = request.POST['todo_notification_time']

    sendEmail(request, receiver_email, notification_time)

    new_item = Todo(
        todo_text=request.POST['todo_text'],
        date_created=parser.parse(request.POST['date_created']).isoformat(),
        due_date=parser.parse(request.POST['due_date']).isoformat(),
        category_id=request.POST['todo_category'],
        email_notification=receiver_email,
        notification_time=notification_time
    )

    try:
        new_item.full_clean()  # Trigger validation
    except ValidationError as e:
        # Handle validation errors
        error_message = str(e)  # Get the error message
        # You can redirect to a specific page or render a response with the error message

    new_item.save()  # Save the instance if validation succeeds

    category_id = request.POST['todo_category']
    category = get_object_or_404(Category, pk=category_id)
    category.todo_count += 1
    category.save()

    return redirect("/todos")



def addCategory(request):
    new_category = Category(category_name = request.POST['category_name'])
    new_category.save()
    return redirect("/todos")


def edit(request, todo_id):
    if request.path == "/todos/" + str(todo_id) + "/edit/":
        hide_side_bar = True

    todo = get_object_or_404(Todo, pk=todo_id)
    due_date = todo.due_date.strftime("%m/%d/%Y %I:%M %p")
    splited_due_date_string = due_date.split(" ")

    context = {
        'todo_id' : todo_id,
        'todo_text' : todo.todo_text,
        'due_date': splited_due_date_string[0] + str().join(" ") + splited_due_date_string[1] + str().join(" ") + splited_due_date_string[2],
        'hideSideBar' : hide_side_bar
    }
    return render(request, 'todos/edit.html', context)


def update(request, todo_id):

    edited_item = request.POST['todo_text']
    edited_due_date = (parser.parse(request.POST['due_date'])).isoformat()
    todo = get_object_or_404(Todo, pk=todo_id)
    todo.todo_text = edited_item
    todo.due_date = edited_due_date
    todo.save()

    return redirect("/todos")


def delete(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    Todo.delete(todo)

    category = get_object_or_404(Category, pk= todo.category_id)
    category.todo_count -= 1
    category.save()
    return redirect("/todos")


def sendEmail(request, receiver_email, notification_time):

    email_body = """
    You have added a new todo_item.
    You can edit and delete the todo_item anytime.
    Your item will expire in """ + str(notification_time) + "!"

    send_mail(
        'Todo_Notification',
        email_body,
        'noreply@todo_application.ca',
        [receiver_email],
        fail_silently=True,
    )
    return HttpResponse('Mail successfully sent')


def check_time(delay, task):
  next_time = time.time() + delay
  while True:
    time.sleep(max(0, next_time - time.time()))
    try:
      task()
    except Exception:
      traceback.print_exc()
    # skip tasks if we are behind schedule:
    next_time += (time.time() - next_time) // delay * delay + delay

def is_expired():
    connection = sqlite3.connect('db.sqlite3')
    cursor = connection.cursor()
    cursor.execute("SELECT * FROM todos_todo WHERE email_notification != '' AND notification_time != 'None' AND sent_reminder == 'False'")
    rows = cursor.fetchall()

    for row in rows:
        todo_item_id = row[0]
        due_date_in_ms = int(datetime.fromisoformat(row[3]).timestamp() * 1000)
        current_date = int(datetime.now().timestamp() * 1000)
        splited_notification_time = str(row[6]).split(" ")
        receiver_email = row[5]
        sent_reminder = row[7]
        date_in_pst = due_date_in_ms - (7 * 60 * 60 * 1000)
        time_remaining = date_in_pst - current_date

        if len(splited_notification_time) == 2:
            if splited_notification_time[1] == "minutes":
                todo_notify_time = int(splited_notification_time[0]) * 60 * 1000
            elif splited_notification_time[1] == "hours":
                todo_notify_time = int(splited_notification_time[0]) * 60 * 60 * 1000
            elif splited_notification_time[1] == "day":
                todo_notify_time = int(splited_notification_time[0]) * 60 * 60 * 24 * 1000
            else:
                continue
        else:
            continue

        if time_remaining <= todo_notify_time:
            todo_item_expire = f"Your todo_item name - {row[1]} will expire in {row[6]}!"
            send_mail(
                'Todo_Notification',
                todo_item_expire,
                'noreply@todo_application.ca',
                [receiver_email],
                fail_silently=False,
            )

            selected_todo_item = get_object_or_404(Todo, pk=int(todo_item_id))
            selected_todo_item.sent_reminder = "True"
            selected_todo_item.save()

threading.Thread(target=lambda: check_time(1, is_expired)).start()

todos/templates/todos/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap 5 CSS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!-- Bootstrap 4 -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>

    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js"></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css\bootstrap.min.css' %}">
 

   <!-- <link rel="stylesheet" href="../../static/todos/sidebar.css">
   <link rel="stylesheet" href="../../static/todos/edit_dialog.css"> -->
    <!-- <link rel="stylesheet" href="https://todo-app-python-django.scm.azurewebsites.net/wwwroot/todos/static/todos/sidebar.css">
    <link rel="stylesheet" href="https://todo-app-python-django.scm.azurewebsites.net/wwwroot/todos/static/todos/edit_dialog.css"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>


    <title>Task Keeper</title>
  </head>
  <body>


 
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary" data-bs-theme="dark">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor03">
          <ul class="navbar-nav me-auto">
            {% if category_items %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">LIST OF AVAILABLE CATEGORIES</a>
              <div class="dropdown-menu" data-popper-placement="bottom-start">
                <div style="padding: 10px; padding-top: 0 auto;">
                  <p style="display: inline;">Category List</p>
                  {% for category in category_items %}
                  <br>
                  <a href="#category" class="category_list" data-toggle="modal" data-target="#{{ category.category_name }}">
                    {% if category.category_name == "Personal" %}
                      <i class="fa fa-home"></i>
                    {% elif category.category_name == "Office" %}
                      <i class="fa fa-laptop"></i>
                    {% elif category.category_name == "Travel" %}
                      <i class="fa fa-plane"></i>
                    {% else %}
                      <i class="fa fa-list-ul"></i>
                    {% endif %}
                    <span class="category_name">{{ category.category_name }}</span>
                    <span class="todo_count">{{ category.todo_count }}</span>
                  </a>
                  {% endfor %}
                </div>
              </div>
            </li>
            {% endif %}
            {% if show_add_task %}
            <li class="nav-item">
              <a href="#" data-toggle="modal" data-target="#myModal" class="nav-link active">
                <i class="fa fa-plus"></i>
                <span class="addTask">Add Task</span>
              </a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a href="#" data-toggle="modal" data-target="#category_Modal" class="nav-link active">
                <i class="fa fa-plus"></i>
                <span class="addCategory">Add Category</span>
              </a>
            </li>
          </ul>
          <form class="d-flex" method="POST" action="{% url 'todos:search' %}">
            {% csrf_token %}
            <input class="form-control me-sm-2" type="search" placeholder="Search" aria-label="Search" name="searched">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    
    

  
  
  <script>
    var active_timer;
    function timer_interval(todo_id, due_date) {
      active_timer = setInterval(function() {
        timer(todo_id, due_date);
      }, 1000);
    }

    function timer(todo_id, due_date){

      var countDownDate = new Date(due_date).getTime();
      var now = new Date().getTime();
      var distance = countDownDate - now;

      // Time calculations for days, hours, minutes and seconds
      var days = Math.floor(distance / (1000 * 60 * 60 * 24));
      var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
      var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
      var seconds = Math.floor((distance % (1000 * 60)) / 1000);

      $(".todo_item" + todo_id).html("Time Remaining : " + days + "d " + hours + "h " + minutes + "m " + seconds + "s ");
      $(".todo_item" + todo_id).css("color", "green");

      if (distance < 0) {
        clearInterval(active_timer);
        $(".todo_item" + todo_id).html("");
      }
    }

  </script>

  {% block body %}
  {% endblock %}

  <script>
    $(function () {
      $("#dateCreated").datetimepicker();
      $("#dueDate").datetimepicker();
    });
  </script>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
  
</html>

todos/templates/todos/edit.html
{% extends 'todos/base.html' %}
{% load static %}

{% block body %}
<link rel="stylesheet" type="text/css" href="{% static 'todos/style.css' %}">
<div class="dialog_container">
  <!-- The Modal -->
  <div class="dialog" id="edit_todo_dialog">
    <!-- Modal Header -->
    <div class="dialog_header">
      
    </div>

    <!-- Modal body -->
    <div class="row justify-content-center" style="padding-top: 50px;" >
    <div class="card text-white bg-primary mb-3" style="max-width: 50rem;height: fit-content;">
      <div class="dialog_header" style="padding: 10px;">
        <h4 class="dialog_title">Edit Todo_Item</h4>
        <hr>
      </div>
      
      <div class="card-body">
        
        <div class="dialog-body">
          <div class="todo_edit_form">
            <form action="{% url 'todos:update' todo_id %}" method="post">
              {% csrf_token %}
              <div class="form-group">
                <p>TASK NAME</p>
                <input type="text" class="form-control" name="todo_text" value="{{ todo_text }}"><br>
                <P style="display: inline;">DUE DATE</P>
                <div class="input-group date" id="dateCreated" data-target-input="nearest" style="top: 1.5em;">
                
                  <input type="text" class="form-control datetimepicker-input" name="due_date" value="{{ due_date }}" data-target="#dateCreated" >
                  <div class="input-group-append" data-target="#dateCreated" data-toggle="datetimepicker"              >
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                  </div>
                </div>
              </div>

            <br><br>
              <div class="dialog_footer">
                <button type="submit" class="btn btn-secondary">Save &amp; Close</button>
                <a href="/todos" class="btn btn-danger">Close</a>
                <input type=button value="<--  Go Back to the previous page" onClick="window.history.back();return false;"  class="btn btn-success" style="padding: 5px;">
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>
{% endblock %}

todos/templates/todos/index.html
{% extends 'todos/base.html' %}

{% block body %}
<style>
  @keyframes blink {
  0% {
    opacity: 1;
  }
  50% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}

.blinking {
  /* animation: blink 1s infinite; */
}

</style>

<h2 class="applicationHeader" style="text-align: center;margin-top: 20px;">Task Keeper: Personal Tasks Management System</h2>
<hr>
<div class="todoItems">
  
  {% if todo_items %}
  <body class="d-flex flex-column min-vh-100">
    <div class="container">
      <div class="row justify-content-centerx">
        {% for todo in todo_items %}

        <div class="col-md-4" > 
          <div class="card text-white bg-secondary mb-3" >
              <div class="card mb-3">
              <div class="card-header blinking">TASKS RECORDED</div> <!-- Added 'blinking' class -->
              <div class="card-body">
              <div class="todoText">
                  <p style="display: inline;">Task Required: </p>
                  <p style="display: inline-block;">{{todo.todo_text}}</p>
                  <p><i class="fa fa-calendar"></i>{{todo.due_date}}</p>
              </div>
              <div class="editAndDeleteButton">
                  <button class="btn btn-primary"><a href="{% url 'todos:edit' todo.id %}"><i class="fa fa-edit"></i></a></button>
                  <button class="btn btn-primary"><a href="{% url 'todos:delete' todo.id %}"><i class="fa fa-trash"></i></a></button>
              </div>
              <br>
              <div class="card-footer text-muted">
                  <script>
                  // Function to calculate the time remaining
                  function getTimeRemaining(endTime) {
                      const total = Date.parse(endTime) - Date.parse(new Date());
                      const seconds = Math.floor((total / 1000) % 60);
                      const minutes = Math.floor((total / 1000 / 60) % 60);
                      const hours = Math.floor((total / (1000 * 60 * 60)) % 24);
                      const days = Math.floor(total / (1000 * 60 * 60 * 24));
              
                      return {
                      total,
                      days,
                      hours,
                      minutes,
                      seconds,
                      };
                  }
              
                  // Function to update the timer display
                  function updateTimer(id, endTime) {
                      const todoElement = document.querySelector(`.todo_item${id}`);
              
                      const time = getTimeRemaining(endTime);
              
                      // Check if due date has passed
                      if (time.total <= 0) {
                      todoElement.style.color = "red";
                      todoElement.textContent = "Due date has already passed";
                      return;
                      }
              
                      // Format the remaining time as a string
                      const remainingTime = `${time.days}d ${time.hours}h ${time.minutes}m ${time.seconds}s`;
              
                      todoElement.textContent = remainingTime;

                      // Check if the remaining time is within the last 5 minutes (300 seconds)
                      // changed from 300s to 30s
                      if (time.total <= 30) {
                          toggleBlinkingHeader(true); // Enable blinking
                      } else {
                          toggleBlinkingHeader(false); // Disable blinking
                      }
                  }
                  
                  // Function to toggle the blinking effect on the card header
                  function toggleBlinkingHeader(enable) {
                      const cardHeader = document.querySelector('.card-header');
                      if (enable) {
                          cardHeader.classList.add('blinking');
                          cardHeader.style.color = 'red'; // Set the text color to red
                      } else {
                          cardHeader.classList.remove('blinking');
                          cardHeader.style.color = ''; // Remove the custom text color
                      }
                  }

                  // Function to set the interval and update the timer
                  function timerInterval(id, endTime) {
                      const interval = setInterval(() => {
                      updateTimer(id, endTime);
              
                      // Check if the due date has passed and clear the interval
                      const time = getTimeRemaining(endTime);
                      if (time.total <= 0) {
                          clearInterval(interval);
                      }
                      }, 1000); // Update the timer every second
                  }
              
                  // Call the timerInterval function with the provided values
                  timerInterval("{{todo.id}}", "{{ todo.due_date|date:"M, d, Y H:i:s" }}");
                  </script>
                  <p style="text-align: center" class="todo_item{{todo.id}}"></p>
              </div>
              </div>
          </div>
      </div>
      </div>
      {% endfor %}
  </div>
</div>
</div>
{% endif %}

</div>

<div class="container">
  <!-- The Modal -->
  <div class="modal" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Add New Task</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <!-- Modal body -->
        <div class="modal-body">
          <div class="todoForm">
            <form action="{% url 'todos:addTodo' %}" method="post" id="addTodoForm">
              {% csrf_token %}
              <div class="form-group">
                <label for="addTodo">What do you want to add?</label>
                <input type="text" class="form-control" id="addTodo" name="todo_text" placeholder="Description" required>
              </div>
              <div class="form-group" style="margin-top: 1em;">
                <label for="email_notification">Would you like to get email notification? (Optional)</label>
                <input type="email" class="form-control" id="email_notification" name="email_notification" placeholder="example@example.com">
              </div>
              <br>
              <div class="form-group">
                <label>Select a category:</label>
                <select style="width: 30%;" name="todo_category" required>
                  {% for category in category_items %}
                  <option value="{{category.id}}">{{category.category_name}}</option>
                  {% endfor %}
                </select>
              </div>
              <br>
              <div class="dateField">
                <div class="input-group date" id="dateCreated" data-target-input="nearest">
                  <input type="text" class="form-control datetimepicker-input" name="date_created" value="{{current_date}}" placeholder="Date created" data-target="#dateCreated" required>
                  <div class="input-group-append" data-target="#dateCreated" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                  </div>
                </div>
                
                <div class="input-group date" id="dueDate" data-target-input="nearest">
                  <input type="text" class="form-control datetimepicker-input" name="due_date" placeholder="Due date" data-target="#dueDate" required>
                  <div class="input-group-append" data-target="#dueDate" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                  </div>
                  <div class="invalid-feedback">Please enter a due date.</div>
                </div>
              </div>
              <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Add</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <!-- The Modal -->
{% for category in category_items %}
  <div class="modal" id={{category.category_name}}>
    <div class="modal-dialog">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Items In {{category.category_name}} Category</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body">
          {% for todo in todo_items %}
            {% if todo.category_id  == category.id %}
              <p>{{todo.todo_text}}</p>
            {% endif %}
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
{% endfor %}
</div>
</div>
</div>
<div class="container">
  <!-- The Modal -->
  <div class="modal" id="category_Modal">
    <div class="modal-dialog">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Create Category</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>

        <!-- Modal body -->
        <div class="modal-body">
          <div class="categoryForm">
            <form action="{% url 'todos:addCategory' %}" method="post">
              {% csrf_token %}
              <div class="form-group">
                <label for="addTodo">Which category do you want to add?</label>
                <input type="text" class="form-control" id="addCategory" name="category_name" placeholder="Description">
              </div>
              <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Add</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  // Client-side form validation
  (function() {
    'use strict';
    // Fetch the addTodoForm element
    var addTodoForm = document.getElementById('addTodoForm');
    // Add a submit event listener to the form
    addTodoForm.addEventListener('submit', function(event) {
      // Retrieve the due date input element
      var dueDateInput = document.getElementById('dueDate');
      // Check if the due date is empty
      if (dueDateInput.value === '') {
        // Prevent the form from submitting
        event.preventDefault();
        // Add the 'is-invalid' class to the input element
        dueDateInput.classList.add('is-invalid');
      }
    });
  })();
</script>
{% endblock %}